# Site Settings
title: "Duc Giang"
description: "Resume of Duc Giang"
url: "https://ducgiangtran.wordpress.com/"
baseurl: "https://ducgiangtran.github.io/" #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Duc Giang
tagline: Mobile Developer
pic: https://github.com/abc.png #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "Enthusiastic mobile developer with 2 years of experience. Ability to self-study new technologies, eager to learn something new. Able to effectively self-manage during independent projects, as well as collaborate as part of a productive team. I have experience working in the product company, able to withstand stress with work hard."

#sidebar links
email: ducgiangtran.dev@gmail.com
# phone: +84 346 221 669
website: ducgiangtran.wordpress.com #do not add http://
github: ducgiangtrankma
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-119187154-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
